CYCLE = 1000
MAX_TIME = 172800

NODE_SIZE = 100
NODE_COLOR = 'brown'
NODE_LABEL_SIZE = 5
NODE_LABEL_COLOR = 'white'

EDGE_WIDTH = 0.5
EDGE_LABEL_SIZE = 5
EDGE_LABEL_COLOR = 'blue'
EDGE_LABEL_ALPHA = 1
